### ISSUE TITLE
AttributeError: 'ProxyCrawlRequest' object has no attribute 'cb_kwargs'

### ISSUE THREAD

**Issue by sgstq** [proxycrawl/scrapy-proxycrawl-middleware#5]
Hi, when I try to run simple test spider with your middleware I get an exception:
`AttributeError: 'ProxyCrawlRequest' object has no attribute 'cb_kwargs'`
 Scrapy 1.6.0, Python 3.8.1, Windows

**Comment by crawlbase** [comment]
Thanks for reporting the above issue. @slurmpit

Can you provide us with a simple test to reproduce the issue?

**Comment by sgstq** [comment]
@proxycrawl  
 [here you are](https://github.com/slurmpit/proxycrawl_test)
it runs by ` python .\run_spider.py -t="TOKEN"`

**Comment by sgstq** [comment]
removing `cb_kwargs` from [here](https://github.com/proxycrawl/scrapy-proxycrawl-middleware/blob/cdfaa8a6bbdd0b76b076abf418a8d5cdeca98eea/scrapy_proxycrawl/request.py#L102) 
or adding it [here](https://github.com/proxycrawl/scrapy-proxycrawl-middleware/blob/cdfaa8a6bbdd0b76b076abf418a8d5cdeca98eea/scrapy_proxycrawl/request.py#L14)
solves issue

**Comment by crawlbase** [comment]
@slurmpit Thanks for the example. We have tried to reproduce it with your code but we didn't get the above-mentioned error. Please check the below debug report. 

[debug-scrapy-proxycrawl-middleware.txt](https://github.com/proxycrawl/scrapy-proxycrawl-middleware/files/4511791/debug-scrapy-proxycrawl-middleware.txt)

**Comment by sgstq** [comment]
ok, maybe it is only in windows. I described solution which helped me above. You can close issue. But maybe it will be useful for somebody else.

**Comment by crawlbase** [comment]
Ok thanks for your research, closing it for now.
